// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3fJgn0dXrdaxXORAqVox0RQudMnNa7Do',
    appId: '1:674638041005:web:3adfecef44043c702d5b24',
    messagingSenderId: '674638041005',
    projectId: 'smart-mushroom-iot',
    authDomain: 'smart-mushroom-iot.firebaseapp.com',
    databaseURL: 'https://smart-mushroom-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-mushroom-iot.firebasestorage.app',
    measurementId: 'G-VMLFKBMH6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdxKsp1ti6mLk7IAMMwQT_7Lh906Oa9Vs',
    appId: '1:674638041005:android:dc201258a8efeb902d5b24',
    messagingSenderId: '674638041005',
    projectId: 'smart-mushroom-iot',
    databaseURL: 'https://smart-mushroom-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-mushroom-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsJit-gZueL4tty2FSdxCDC2FjKpidWmI',
    appId: '1:674638041005:ios:f94aee931627f88c2d5b24',
    messagingSenderId: '674638041005',
    projectId: 'smart-mushroom-iot',
    databaseURL: 'https://smart-mushroom-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-mushroom-iot.firebasestorage.app',
    iosClientId: '674638041005-hq4ujtf4v63a2721mftrnmaeetqf9naa.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartmushroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsJit-gZueL4tty2FSdxCDC2FjKpidWmI',
    appId: '1:674638041005:ios:f94aee931627f88c2d5b24',
    messagingSenderId: '674638041005',
    projectId: 'smart-mushroom-iot',
    databaseURL: 'https://smart-mushroom-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-mushroom-iot.firebasestorage.app',
    iosClientId: '674638041005-hq4ujtf4v63a2721mftrnmaeetqf9naa.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartmushroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3fJgn0dXrdaxXORAqVox0RQudMnNa7Do',
    appId: '1:674638041005:web:15666eba5a033b412d5b24',
    messagingSenderId: '674638041005',
    projectId: 'smart-mushroom-iot',
    authDomain: 'smart-mushroom-iot.firebaseapp.com',
    databaseURL: 'https://smart-mushroom-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-mushroom-iot.firebasestorage.app',
    measurementId: 'G-H5N0QE7B28',
  );
}
